// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do one of these:
//
//    using Ladesa.Dtos;
//
//    var arquivo = Arquivo.FromJson(jsonString);
//    var arquivoFindOneInputView = ArquivoFindOneInputView.FromJson(jsonString);
//    var arquivoFindOneResultView = ArquivoFindOneResultView.FromJson(jsonString);
//    var arquivoView = ArquivoView.FromJson(jsonString);
//    var datedObject = DatedObject.FromJson(jsonString);
//    var imagem = Imagem.FromJson(jsonString);
//    var imagemArquivo = ImagemArquivo.FromJson(jsonString);
//    var objectIntegerId = ObjectIntegerId.FromJson(jsonString);
//    var objectUuid = ObjectUuid.FromJson(jsonString);
//    var paginationFilterView = PaginationFilterView.FromJson(jsonString);
//    var paginationInputBaseView = PaginationInputBaseView.FromJson(jsonString);
//    var paginationInputView = PaginationInputView.FromJson(jsonString);
//    var paginationResultLinks = PaginationResultLinks.FromJson(jsonString);
//    var paginationResultMeta = PaginationResultMeta.FromJson(jsonString);
//    var paginationSortByView = PaginationSortByView.FromJson(jsonString);
//    var tokens = Tokens.FromJson(jsonString);
//    var usuario = Usuario.FromJson(jsonString);
//    var dateTime = DateTime.FromJson(jsonString);
//    var uuid = Uuid.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace Ladesa.Dtos
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    /// <summary>
    /// Arquivo.
    /// </summary>
    public partial class Arquivo
    {
        /// <summary>
        /// Data e hora da criação do registro.
        /// </summary>
        [JsonPropertyName("dateCreated")]
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Data e hora da exclusão do registro.
        /// </summary>
        [JsonPropertyName("dateDeleted")]
        public DateTimeOffset? DateDeleted { get; set; }

        /// <summary>
        /// Data e hora da alteração do registro.
        /// </summary>
        [JsonPropertyName("dateUpdated")]
        public DateTimeOffset DateUpdated { get; set; }

        /// <summary>
        /// Identificador do registro (uuid).
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Formato do arquivo.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("mimeType")]
        public string MimeType { get; set; }

        /// <summary>
        /// Nome do arquivo.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("nome")]
        public string Nome { get; set; }

        /// <summary>
        /// Tamanho do arquivo (em bytes).
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("sizeBytes")]
        public long? SizeBytes { get; set; }

        /// <summary>
        /// Estratégia de armazenamento do conteúdo.
        /// </summary>
        [JsonPropertyName("storageType")]
        public string StorageType { get; set; }
    }

    /// <summary>
    /// Dados de entrada para encontrar um Arquivo por ID.
    /// </summary>
    public partial class ArquivoFindOneInputView
    {
        /// <summary>
        /// Identificador do registro (uuid).
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }
    }

    /// <summary>
    /// Dados de saída para encontrar um Arquivo por ID.
    /// </summary>
    public partial class ArquivoFindOneResultView
    {
        /// <summary>
        /// Data e hora da criação do registro.
        /// </summary>
        [JsonPropertyName("dateCreated")]
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Data e hora da exclusão do registro.
        /// </summary>
        [JsonPropertyName("dateDeleted")]
        public DateTimeOffset? DateDeleted { get; set; }

        /// <summary>
        /// Data e hora da alteração do registro.
        /// </summary>
        [JsonPropertyName("dateUpdated")]
        public DateTimeOffset DateUpdated { get; set; }

        /// <summary>
        /// Identificador do registro (uuid).
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Formato do arquivo.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("mimeType")]
        public string MimeType { get; set; }

        /// <summary>
        /// Nome do arquivo.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("nome")]
        public string Nome { get; set; }

        /// <summary>
        /// Tamanho do arquivo (em bytes).
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("sizeBytes")]
        public long? SizeBytes { get; set; }

        /// <summary>
        /// Estratégia de armazenamento do conteúdo.
        /// </summary>
        [JsonPropertyName("storageType")]
        public string StorageType { get; set; }
    }

    /// <summary>
    /// Visão completa de um Arquivo.
    /// </summary>
    public partial class ArquivoView
    {
        /// <summary>
        /// Data e hora da criação do registro.
        /// </summary>
        [JsonPropertyName("dateCreated")]
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Data e hora da exclusão do registro.
        /// </summary>
        [JsonPropertyName("dateDeleted")]
        public DateTimeOffset? DateDeleted { get; set; }

        /// <summary>
        /// Data e hora da alteração do registro.
        /// </summary>
        [JsonPropertyName("dateUpdated")]
        public DateTimeOffset DateUpdated { get; set; }

        /// <summary>
        /// Identificador do registro (uuid).
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Formato do arquivo.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("mimeType")]
        public string MimeType { get; set; }

        /// <summary>
        /// Nome do arquivo.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("nome")]
        public string Nome { get; set; }

        /// <summary>
        /// Tamanho do arquivo (em bytes).
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("sizeBytes")]
        public long? SizeBytes { get; set; }

        /// <summary>
        /// Estratégia de armazenamento do conteúdo.
        /// </summary>
        [JsonPropertyName("storageType")]
        public string StorageType { get; set; }
    }

    /// <summary>
    /// Estrutura datada.
    /// </summary>
    public partial class DatedObject
    {
        /// <summary>
        /// Data e hora da criação do registro.
        /// </summary>
        [JsonPropertyName("dateCreated")]
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Data e hora da exclusão do registro.
        /// </summary>
        [JsonPropertyName("dateDeleted")]
        public DateTimeOffset? DateDeleted { get; set; }

        /// <summary>
        /// Data e hora da alteração do registro.
        /// </summary>
        [JsonPropertyName("dateUpdated")]
        public DateTimeOffset DateUpdated { get; set; }
    }

    /// <summary>
    /// Imagem.
    /// </summary>
    public partial class Imagem
    {
        /// <summary>
        /// Data e hora da criação do registro.
        /// </summary>
        [JsonPropertyName("dateCreated")]
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Data e hora da exclusão do registro.
        /// </summary>
        [JsonPropertyName("dateDeleted")]
        public DateTimeOffset? DateDeleted { get; set; }

        /// <summary>
        /// Data e hora da alteração do registro.
        /// </summary>
        [JsonPropertyName("dateUpdated")]
        public DateTimeOffset DateUpdated { get; set; }

        /// <summary>
        /// Descrição da imagem.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("descricao")]
        public string Descricao { get; set; }

        /// <summary>
        /// Identificador do registro (uuid).
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }
    }

    /// <summary>
    /// ImagemArquivo.
    /// </summary>
    public partial class ImagemArquivo
    {
        /// <summary>
        /// Altura da imagem.
        /// </summary>
        [JsonPropertyName("altura")]
        public long Altura { get; set; }

        /// <summary>
        /// Arquivo.
        /// </summary>
        [JsonPropertyName("arquivo")]
        public ArquivoClass Arquivo { get; set; }

        /// <summary>
        /// Data e hora da criação do registro.
        /// </summary>
        [JsonPropertyName("dateCreated")]
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Data e hora da exclusão do registro.
        /// </summary>
        [JsonPropertyName("dateDeleted")]
        public DateTimeOffset? DateDeleted { get; set; }

        /// <summary>
        /// Data e hora da alteração do registro.
        /// </summary>
        [JsonPropertyName("dateUpdated")]
        public DateTimeOffset DateUpdated { get; set; }

        /// <summary>
        /// Formato da imagem.
        /// </summary>
        [JsonPropertyName("formato")]
        public string Formato { get; set; }

        /// <summary>
        /// Identificador do registro (uuid).
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Imagem.
        /// </summary>
        [JsonPropertyName("imagem")]
        public ImagemClass Imagem { get; set; }

        /// <summary>
        /// Largura da imagem.
        /// </summary>
        [JsonPropertyName("largura")]
        public long Largura { get; set; }

        /// <summary>
        /// Mime-type da imagem.
        /// </summary>
        [JsonPropertyName("mimeType")]
        public string MimeType { get; set; }
    }

    /// <summary>
    /// Arquivo.
    /// </summary>
    public partial class ArquivoClass
    {
        /// <summary>
        /// Data e hora da criação do registro.
        /// </summary>
        [JsonPropertyName("dateCreated")]
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Data e hora da exclusão do registro.
        /// </summary>
        [JsonPropertyName("dateDeleted")]
        public DateTimeOffset? DateDeleted { get; set; }

        /// <summary>
        /// Data e hora da alteração do registro.
        /// </summary>
        [JsonPropertyName("dateUpdated")]
        public DateTimeOffset DateUpdated { get; set; }

        /// <summary>
        /// Identificador do registro (uuid).
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Formato do arquivo.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("mimeType")]
        public string MimeType { get; set; }

        /// <summary>
        /// Nome do arquivo.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("nome")]
        public string Nome { get; set; }

        /// <summary>
        /// Tamanho do arquivo (em bytes).
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("sizeBytes")]
        public long? SizeBytes { get; set; }

        /// <summary>
        /// Estratégia de armazenamento do conteúdo.
        /// </summary>
        [JsonPropertyName("storageType")]
        public string StorageType { get; set; }
    }

    /// <summary>
    /// Imagem.
    ///
    /// Imagem de capa do usuário.
    ///
    /// Imagem de perfil do usuário.
    /// </summary>
    public partial class ImagemClass
    {
        /// <summary>
        /// Data e hora da criação do registro.
        /// </summary>
        [JsonPropertyName("dateCreated")]
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Data e hora da exclusão do registro.
        /// </summary>
        [JsonPropertyName("dateDeleted")]
        public DateTimeOffset? DateDeleted { get; set; }

        /// <summary>
        /// Data e hora da alteração do registro.
        /// </summary>
        [JsonPropertyName("dateUpdated")]
        public DateTimeOffset DateUpdated { get; set; }

        /// <summary>
        /// Descrição da imagem.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("descricao")]
        public string Descricao { get; set; }

        /// <summary>
        /// Identificador do registro (uuid).
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }
    }

    /// <summary>
    /// Estrutura identificada por id no formato numérico.
    /// </summary>
    public partial class ObjectIntegerId
    {
        /// <summary>
        /// Identificador do registro (numérico).
        /// </summary>
        [JsonPropertyName("id")]
        public long Id { get; set; }
    }

    /// <summary>
    /// Estrutura identificada por id no formato uuid.
    /// </summary>
    public partial class ObjectUuid
    {
        /// <summary>
        /// Identificador do registro (uuid).
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }
    }

    /// <summary>
    /// Configuração de filtro por restrições de uma propriedade.
    /// </summary>
    public partial class PaginationFilterView
    {
        /// <summary>
        /// Propriedade filtrada.
        /// </summary>
        [JsonPropertyName("property")]
        public string Property { get; set; }

        /// <summary>
        /// Restrições de filtragem.
        /// </summary>
        [JsonPropertyName("restrictions")]
        public string[] Restrictions { get; set; }
    }

    public partial class PaginationInputBaseView
    {
        /// <summary>
        /// Limite da quantidade de resultados por página.
        /// </summary>
        [JsonPropertyName("limit")]
        public long? Limit { get; set; }

        /// <summary>
        /// Página de consulta.
        /// </summary>
        [JsonPropertyName("page")]
        public long? Page { get; set; }

        /// <summary>
        /// Busca textual.
        /// </summary>
        [JsonPropertyName("search")]
        public string Search { get; set; }
    }

    public partial class PaginationInputView
    {
        /// <summary>
        /// Filtros.
        /// </summary>
        [JsonPropertyName("filter")]
        public FilterElement[] Filter { get; set; }

        /// <summary>
        /// Limite da quantidade de resultados por página.
        /// </summary>
        [JsonPropertyName("limit")]
        public long? Limit { get; set; }

        /// <summary>
        /// Página de consulta.
        /// </summary>
        [JsonPropertyName("page")]
        public long? Page { get; set; }

        /// <summary>
        /// Busca textual.
        /// </summary>
        [JsonPropertyName("search")]
        public string Search { get; set; }

        /// <summary>
        /// Ordenação.
        /// </summary>
        [JsonPropertyName("sortBy")]
        public SortByElement[] SortBy { get; set; }
    }

    /// <summary>
    /// Configuração de filtro por restrições de uma propriedade.
    /// </summary>
    public partial class FilterElement
    {
        /// <summary>
        /// Propriedade filtrada.
        /// </summary>
        [JsonPropertyName("property")]
        public string Property { get; set; }

        /// <summary>
        /// Restrições de filtragem.
        /// </summary>
        [JsonPropertyName("restrictions")]
        public string[] Restrictions { get; set; }
    }

    /// <summary>
    /// Configuração de ordenação de uma propriedade.
    /// </summary>
    public partial class SortByElement
    {
        /// <summary>
        /// Modo de ordenação.
        /// </summary>
        [JsonPropertyName("mode")]
        public string Mode { get; set; }

        /// <summary>
        /// Propriedade ordenada.
        /// </summary>
        [JsonPropertyName("property")]
        public string Property { get; set; }
    }

    public partial class PaginationResultLinks
    {
        [JsonPropertyName("current")]
        public string Current { get; set; }

        [JsonPropertyName("first")]
        public string First { get; set; }

        [JsonPropertyName("last")]
        public string Last { get; set; }

        [JsonPropertyName("next")]
        public string Next { get; set; }

        [JsonPropertyName("previous")]
        public string Previous { get; set; }
    }

    /// <summary>
    /// Metadados dos resultados de busca.
    /// </summary>
    public partial class PaginationResultMeta
    {
        /// <summary>
        /// Página atual.
        /// </summary>
        [JsonPropertyName("currentPage")]
        public long CurrentPage { get; set; }

        /// <summary>
        /// Filtros.
        /// </summary>
        [JsonPropertyName("filter")]
        public FilterElement[] Filter { get; set; }

        /// <summary>
        /// Quantidade de itens por página.
        /// </summary>
        [JsonPropertyName("itemsPerPage")]
        public long ItemsPerPage { get; set; }

        /// <summary>
        /// Termo textual da busca.
        /// </summary>
        [JsonPropertyName("search")]
        public string Search { get; set; }

        /// <summary>
        /// Ordenação.
        /// </summary>
        [JsonPropertyName("sortBy")]
        public SortByElement[] SortBy { get; set; }

        /// <summary>
        /// Total de itens.
        /// </summary>
        [JsonPropertyName("totalItems")]
        public long TotalItems { get; set; }

        /// <summary>
        /// Quantidade total de páginas.
        /// </summary>
        [JsonPropertyName("totalPages")]
        public long TotalPages { get; set; }
    }

    /// <summary>
    /// Configuração de ordenação de uma propriedade.
    /// </summary>
    public partial class PaginationSortByView
    {
        /// <summary>
        /// Modo de ordenação.
        /// </summary>
        [JsonPropertyName("mode")]
        public string Mode { get; set; }

        /// <summary>
        /// Propriedade ordenada.
        /// </summary>
        [JsonPropertyName("property")]
        public string Property { get; set; }
    }

    /// <summary>
    /// Usuário.
    /// </summary>
    public partial class Usuario
    {
        /// <summary>
        /// Data e hora da criação do registro.
        /// </summary>
        [JsonPropertyName("dateCreated")]
        public DateTimeOffset DateCreated { get; set; }

        /// <summary>
        /// Data e hora da exclusão do registro.
        /// </summary>
        [JsonPropertyName("dateDeleted")]
        public DateTimeOffset? DateDeleted { get; set; }

        /// <summary>
        /// Data e hora da alteração do registro.
        /// </summary>
        [JsonPropertyName("dateUpdated")]
        public DateTimeOffset DateUpdated { get; set; }

        /// <summary>
        /// E-mail do usuário.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// Identificador do registro (uuid).
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Imagem de capa do usuário.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("imagemCapa")]
        public ImagemClass ImagemCapa { get; set; }

        /// <summary>
        /// Imagem de perfil do usuário.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("imagemPerfil")]
        public ImagemClass ImagemPerfil { get; set; }

        /// <summary>
        /// Diz que o usuário tem poderes de administrador.
        /// </summary>
        [JsonPropertyName("isSuperUser")]
        public bool IsSuperUser { get; set; }

        /// <summary>
        /// Matrícula SIAPE do usuário.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("matriculaSiape")]
        public string MatriculaSiape { get; set; }

        /// <summary>
        /// Nome do usuário.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("nome")]
        public string Nome { get; set; }
    }

    /// <summary>
    /// Define os nomes de indentificação das entidades.
    /// </summary>
    public enum TokensEnum { Arquivo, ArquivoFindOneInputView, ArquivoFindOneResultView, ArquivoView, Imagem, ImagemArquivo, PaginatedFilterView, PaginatedInputBaseView, PaginatedInputView, PaginatedResultLinksView, PaginatedResultMetaView, PaginatedResultView, PaginatedSortByView, Usuario };

    public partial class Arquivo
    {
        public static Arquivo FromJson(string json) => JsonSerializer.Deserialize<Arquivo>(json, Ladesa.Dtos.Converter.Settings);
    }

    public partial class ArquivoFindOneInputView
    {
        public static ArquivoFindOneInputView FromJson(string json) => JsonSerializer.Deserialize<ArquivoFindOneInputView>(json, Ladesa.Dtos.Converter.Settings);
    }

    public partial class ArquivoFindOneResultView
    {
        public static ArquivoFindOneResultView FromJson(string json) => JsonSerializer.Deserialize<ArquivoFindOneResultView>(json, Ladesa.Dtos.Converter.Settings);
    }

    public partial class ArquivoView
    {
        public static ArquivoView FromJson(string json) => JsonSerializer.Deserialize<ArquivoView>(json, Ladesa.Dtos.Converter.Settings);
    }

    public partial class DatedObject
    {
        public static DatedObject FromJson(string json) => JsonSerializer.Deserialize<DatedObject>(json, Ladesa.Dtos.Converter.Settings);
    }

    public partial class Imagem
    {
        public static Imagem FromJson(string json) => JsonSerializer.Deserialize<Imagem>(json, Ladesa.Dtos.Converter.Settings);
    }

    public partial class ImagemArquivo
    {
        public static ImagemArquivo FromJson(string json) => JsonSerializer.Deserialize<ImagemArquivo>(json, Ladesa.Dtos.Converter.Settings);
    }

    public partial class ObjectIntegerId
    {
        public static ObjectIntegerId FromJson(string json) => JsonSerializer.Deserialize<ObjectIntegerId>(json, Ladesa.Dtos.Converter.Settings);
    }

    public partial class ObjectUuid
    {
        public static ObjectUuid FromJson(string json) => JsonSerializer.Deserialize<ObjectUuid>(json, Ladesa.Dtos.Converter.Settings);
    }

    public partial class PaginationFilterView
    {
        public static PaginationFilterView FromJson(string json) => JsonSerializer.Deserialize<PaginationFilterView>(json, Ladesa.Dtos.Converter.Settings);
    }

    public partial class PaginationInputBaseView
    {
        public static PaginationInputBaseView FromJson(string json) => JsonSerializer.Deserialize<PaginationInputBaseView>(json, Ladesa.Dtos.Converter.Settings);
    }

    public partial class PaginationInputView
    {
        public static PaginationInputView FromJson(string json) => JsonSerializer.Deserialize<PaginationInputView>(json, Ladesa.Dtos.Converter.Settings);
    }

    public partial class PaginationResultLinks
    {
        public static PaginationResultLinks FromJson(string json) => JsonSerializer.Deserialize<PaginationResultLinks>(json, Ladesa.Dtos.Converter.Settings);
    }

    public partial class PaginationResultMeta
    {
        public static PaginationResultMeta FromJson(string json) => JsonSerializer.Deserialize<PaginationResultMeta>(json, Ladesa.Dtos.Converter.Settings);
    }

    public partial class PaginationSortByView
    {
        public static PaginationSortByView FromJson(string json) => JsonSerializer.Deserialize<PaginationSortByView>(json, Ladesa.Dtos.Converter.Settings);
    }

    public class Tokens
    {
        public static TokensEnum FromJson(string json) => JsonSerializer.Deserialize<TokensEnum>(json, Ladesa.Dtos.Converter.Settings);
    }

    public partial class Usuario
    {
        public static Usuario FromJson(string json) => JsonSerializer.Deserialize<Usuario>(json, Ladesa.Dtos.Converter.Settings);
    }

    public class DateTime
    {
        public static DateTimeOffset FromJson(string json) => JsonSerializer.Deserialize<DateTimeOffset>(json, Ladesa.Dtos.Converter.Settings);
    }

    public class Uuid
    {
        public static Guid FromJson(string json) => JsonSerializer.Deserialize<Guid>(json, Ladesa.Dtos.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Arquivo self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this ArquivoFindOneInputView self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this ArquivoFindOneResultView self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this ArquivoView self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this DatedObject self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this Imagem self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this ImagemArquivo self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this ObjectIntegerId self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this ObjectUuid self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this PaginationFilterView self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this PaginationInputBaseView self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this PaginationInputView self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this PaginationResultLinks self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this PaginationResultMeta self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this PaginationSortByView self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this TokensEnum self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this Usuario self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this DateTimeOffset self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
        public static string ToJson(this Guid self) => JsonSerializer.Serialize(self, Ladesa.Dtos.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                TokensEnumConverter.Singleton,
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    internal class TokensEnumConverter : JsonConverter<TokensEnum>
    {
        public override bool CanConvert(Type t) => t == typeof(TokensEnum);

        public override TokensEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "Arquivo":
                    return TokensEnum.Arquivo;
                case "ArquivoFindOneInputView":
                    return TokensEnum.ArquivoFindOneInputView;
                case "ArquivoFindOneResultView":
                    return TokensEnum.ArquivoFindOneResultView;
                case "ArquivoView":
                    return TokensEnum.ArquivoView;
                case "Imagem":
                    return TokensEnum.Imagem;
                case "ImagemArquivo":
                    return TokensEnum.ImagemArquivo;
                case "PaginatedFilterView":
                    return TokensEnum.PaginatedFilterView;
                case "PaginatedInputBaseView":
                    return TokensEnum.PaginatedInputBaseView;
                case "PaginatedInputView":
                    return TokensEnum.PaginatedInputView;
                case "PaginatedResultLinksView":
                    return TokensEnum.PaginatedResultLinksView;
                case "PaginatedResultMetaView":
                    return TokensEnum.PaginatedResultMetaView;
                case "PaginatedResultView":
                    return TokensEnum.PaginatedResultView;
                case "PaginatedSortByView":
                    return TokensEnum.PaginatedSortByView;
                case "Usuario":
                    return TokensEnum.Usuario;
            }
            throw new Exception("Cannot unmarshal type TokensEnum");
        }

        public override void Write(Utf8JsonWriter writer, TokensEnum value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case TokensEnum.Arquivo:
                    JsonSerializer.Serialize(writer, "Arquivo", options);
                    return;
                case TokensEnum.ArquivoFindOneInputView:
                    JsonSerializer.Serialize(writer, "ArquivoFindOneInputView", options);
                    return;
                case TokensEnum.ArquivoFindOneResultView:
                    JsonSerializer.Serialize(writer, "ArquivoFindOneResultView", options);
                    return;
                case TokensEnum.ArquivoView:
                    JsonSerializer.Serialize(writer, "ArquivoView", options);
                    return;
                case TokensEnum.Imagem:
                    JsonSerializer.Serialize(writer, "Imagem", options);
                    return;
                case TokensEnum.ImagemArquivo:
                    JsonSerializer.Serialize(writer, "ImagemArquivo", options);
                    return;
                case TokensEnum.PaginatedFilterView:
                    JsonSerializer.Serialize(writer, "PaginatedFilterView", options);
                    return;
                case TokensEnum.PaginatedInputBaseView:
                    JsonSerializer.Serialize(writer, "PaginatedInputBaseView", options);
                    return;
                case TokensEnum.PaginatedInputView:
                    JsonSerializer.Serialize(writer, "PaginatedInputView", options);
                    return;
                case TokensEnum.PaginatedResultLinksView:
                    JsonSerializer.Serialize(writer, "PaginatedResultLinksView", options);
                    return;
                case TokensEnum.PaginatedResultMetaView:
                    JsonSerializer.Serialize(writer, "PaginatedResultMetaView", options);
                    return;
                case TokensEnum.PaginatedResultView:
                    JsonSerializer.Serialize(writer, "PaginatedResultView", options);
                    return;
                case TokensEnum.PaginatedSortByView:
                    JsonSerializer.Serialize(writer, "PaginatedSortByView", options);
                    return;
                case TokensEnum.Usuario:
                    JsonSerializer.Serialize(writer, "Usuario", options);
                    return;
            }
            throw new Exception("Cannot marshal type TokensEnum");
        }

        public static readonly TokensEnumConverter Singleton = new TokensEnumConverter();
    }
    
    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
