version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "/"
      - "/definitions"
      - "/integrations/npm/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directories:
      - "/.github/actions/*"
      - "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
