name: "Prepare: Install"

description: "Prepares the repo by installing dependencies"

inputs:
  node-version:
    description: "The node version to setup"
    required: true

  registry-url:
    description: "Define registry-url"
    required: false

  working-directory:
    description: "Override the working directory to run the installation in"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: echo github.ref
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: echo ${{ github.ref }}

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - run: corepack enable
      shell: bash

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: "pnpm"

    - uses: google/wireit@setup-github-actions-caching/v2

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm install --frozen-lockfile
      env:
        HUSKY: "0"
