name: "Prepare: Build"
description: "Prepares the repo for a job by running the build"
# inputs:  - no inputs
# outputs: - no outputs

runs:
  using: "composite"
  steps:
    - name: Build core
      shell: bash
      run: pnpm run -r --filter core build

    - name: Run Codegen
      shell: bash
      run: pnpm run -r --filter codegen start

    - name: Build Project for Production
      shell: bash
      run: npx nx run-many --target=build --configuration production --parallel
