name: "Prepare: Build"
description: "Prepares the repo for a job by running the build"
# inputs:  - no inputs
# outputs: - no outputs

runs:
  using: "composite"
  steps:

    - name: Build Project for Production
      shell: bash
      run: npx nx run-many --target=build --parallel
