name: "Prepare: Build"
description: "Prepares the repo for a job by running the build"

inputs:
  workspace_build:
    description: "workspace project build"
    required: false
    default: "false"

  integrations_dotnet_build:
    description: "integrations/dotnet build"
    required: false
    default: "false"

# outputs: - no outputs

runs:
  using: "composite"

  steps:
    - name: "Build: all build scripts"
      if: ${{ inputs.workspace_build == 'true' }}
      shell: bash
      run: pnpm run -w build
      env:
        WIREIT_LOGGER: simple

    - name: "Build: integrations/dotnet"
      if: ${{ inputs.integrations_dotnet_build == 'true' }}
      shell: bash
      working-directory: ./integrations/dotnet
      run: dotnet build --configuration Release
