name: "Prepare: Build"
description: "Prepares the repo for a job by running the build"
# inputs:  - no inputs
# outputs: - no outputs

runs:
  using: "composite"
  steps:
    - name: Run build
      shell: bash
      run: pnpm run -w build
