name: "CI"

on:
  push:
    branches:
      - main
      - development
    paths:
      - "core/**/*"
      - .github/workflows/ci.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: core

permissions:
  contents: read

jobs:
  core-quality:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./core/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test --if-present
      - run: npm audit signatures

  core-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    needs: [core-quality]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: ./core/package-lock.json
      - run: npm ci
      - run: npm run build

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

  integrations-build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    needs: [core-quality]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup docker image prepared with generatejsonschematypes
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:integrations/dotnet/.devops"
          file: "Dockerfile"
          tags: sisgea/generator-dotnet:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
      - name: Run Pytest
        uses: addnab/docker-run-action@v3
        with:
          image: sisgea/generator-dotnet:latest
          options: -v ${{ github.workspace }}:/work
          run: |
            ls /work;
            ls /github/workspace;
          # run: generatejsonschematypes --rootNamespace Sisgea.Spec --outputPath /work/integrations/dotnet/Sisgea.Spec/Generated /work/integrations/json-schema/v1/sisgea.schema.json
