name: CI

on:
  push:
    branches:
      - main
      - next
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: write

env:
  PRIMARY_NODE_VERSION: 20

jobs:
  ci-cd:
    name: CI/CD
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}

      - name: Build
        uses: ./.github/actions/prepare-build

      # - name: Tag branch if all jobs succeed
      #   uses: nrwl/nx-tag-successful-ci-run@v1

      - run: git config user.name 'github-actions[bot]'
      - run: git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Prepare NPM token
        uses: ./.github/actions/prepare-npm-token
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - run: pnpm run -w release:next
        if: github.ref == 'refs/heads/next'
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_TOKEN }}

      - run: pnpm run -w release:main
        if: github.ref == 'refs/heads/main'
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_TOKEN }}

      - run: git push --follow-tags
