name: "CI"

on:
  push:
    branches:
      - main
      - development
    paths:
      - "core/**/*"
      - .github/workflows/ci.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  core-quality:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./core/package-lock.json
      - run: npm ci
        working-directory: core
      - run: npm run build --if-present
        working-directory: core
      - run: npm run test --if-present
        working-directory: core
      - run: npm audit signatures
        working-directory: core

  core-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    needs: [core-quality]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: ./core/package-lock.json
      - run: npm ci
        working-directory: core
      - run: npm run build
        working-directory: core

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
        working-directory: core

  integrations-build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    needs: [core-quality]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install dotnet tool 'Corvus.Json.JsonSchema.TypeGeneratorTool'
        run: dotnet tool install --global Corvus.Json.JsonSchema.TypeGeneratorTool

      - name: Run Pytest
        run: generatejsonschematypes --rootNamespace Sisgea.Spec --outputPath integrations/dotnet/Sisgea.Spec/Generated integrations/json-schema/v1/sisgea.schema.json
