name: "Continuos Release: Publish Any Commit"

on:
  push:
    branches:
      - development
      - production

  pull_request:

  tags:
    - "!**"

env:
  PRIMARY_NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}

      - name: Build
        uses: ./.github/actions/prepare-build

      - run: pnpx pkg-pr-new publish --comment=update './integrations/npm/especificacao'
