name: "Continuos Release: Publish any commit"

on:
  push:
    branches:
      - development
      - production
    tags:
      - "!**"

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          install-node: "true"
          install-dotnet: "true"

      - name: Build
        uses: ./.github/actions/prepare-build
        with:
          workspace_build: "true"

      - name: "Continuos Release: publish to pkg.pr.new"
        run: pnpx pkg-pr-new publish --comment=update './integrations/npm/especificacao'
