name: "Publish to the NPM registry"

on:
  workflow_dispatch:
  push:
    tags:
      - "@ladesa-ro/especificacao@**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  actions: read
  contents: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Tag
        run: echo ${{ github.ref_name }}

      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          install_node: "true"
          install_dotnet: "false"

      - name: Build
        uses: ./.github/actions/prepare-build
        with:
          workspace_build: "true"

      - name: Prepare NPM token
        uses: ./.github/actions/prepare-npm-token
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: pnpm publish -r --no-git-checks
