name: Code quality

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          install-node: "true"
          install-dotnet: "true"

      - name: Check static code quality
        run: pnpm run -w code-static:check
