name: Release

on:
  push:
    branches:
      - development

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  PRIMARY_NODE_VERSION: 20

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      issues: write
      actions: write
      statuses: write
      contents: write
      security-events: write
      pages: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          install_node: "true"
          install_dotnet: "false"
          node-version: ${{ env.PRIMARY_NODE_VERSION }}

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: pnpm run -w changeset:tag
          version: pnpm run -w changeset:version
          commit: "chore: version packages"
          title: "chore: version packages"
          createGithubReleases: false
        env:
          NPM_CONFIG_PROVENANCE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
